@echo off
echo [NYXA] Activating virtual environment...
call .\.venv\Scripts\activate.bat

echo [NYXA] Updating dependencies...
pip install -r requirements.txt

echo [NYXA] Applying database migrations...
alembic upgrade head

echo [NYXA] Starting Bot...
python run.py