@echo off
echo [FAYE] Activating virtual environment...
call .\.venv\Scripts\activate.bat

echo [FAYE] Updating dependencies...
pip install -r requirements.txt

echo [FAYE] Applying database migrations...
alembic upgrade head

echo [FAYE] Starting Bot...
python run.py

