"""Create initial database schema

Revision ID: 1c81f10e2ea1
Revises: 
Create Date: 2025-06-09 07:08:28.088701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c81f10e2ea1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('espritdata',
    sa.Column('esprit_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rarity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('class_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('visual_asset_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_hp', sa.Integer(), nullable=False),
    sa.Column('base_attack', sa.Integer(), nullable=False),
    sa.Column('base_defense', sa.Integer(), nullable=False),
    sa.Column('base_speed', sa.Integer(), nullable=False),
    sa.Column('base_magic_resist', sa.Integer(), nullable=False),
    sa.Column('base_crit_rate', sa.Float(), nullable=False),
    sa.Column('base_block_rate', sa.Float(), nullable=False),
    sa.Column('base_dodge_chance', sa.Float(), nullable=False),
    sa.Column('base_mana_regen', sa.Integer(), nullable=False),
    sa.Column('base_mana', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('esprit_id')
    )
    op.create_index(op.f('ix_espritdata_esprit_id'), 'espritdata', ['esprit_id'], unique=False)
    op.create_table('user',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('nyxies', sa.Integer(), nullable=False),
    sa.Column('moonglow', sa.Integer(), nullable=False),
    sa.Column('azurite_shards', sa.Integer(), nullable=False),
    sa.Column('essence', sa.Integer(), nullable=False),
    sa.Column('loot_chests', sa.Integer(), nullable=False),
    sa.Column('last_daily_claim', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('active_esprit_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('support1_esprit_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('support2_esprit_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['active_esprit_id'], ['useresprit.id'], ),
    sa.ForeignKeyConstraint(['support1_esprit_id'], ['useresprit.id'], ),
    sa.ForeignKeyConstraint(['support2_esprit_id'], ['useresprit.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    op.create_table('useresprit',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('esprit_data_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_hp', sa.Integer(), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.Column('current_xp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['esprit_data_id'], ['espritdata.esprit_id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_useresprit_esprit_data_id'), 'useresprit', ['esprit_data_id'], unique=False)
    op.create_index(op.f('ix_useresprit_owner_id'), 'useresprit', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_useresprit_owner_id'), table_name='useresprit')
    op.drop_index(op.f('ix_useresprit_esprit_data_id'), table_name='useresprit')
    op.drop_table('useresprit')
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_espritdata_esprit_id'), table_name='espritdata')
    op.drop_table('espritdata')
    # ### end Alembic commands ###
