"""Add last_daily_summon to User model

Revision ID: 4da95b51e9ba
Revises: ef4d780dbf46
Create Date: 2025-06-12 17:28:42.965085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4da95b51e9ba'
down_revision: Union[str, None] = 'ef4d780dbf46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # This now correctly targets the 'user' (singular) table.
    op.add_column('user', sa.Column('last_daily_summon', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # The downgrade path is also corrected to target the 'user' (singular) table.
    op.drop_column('user', 'last_daily_summon')
    # ### end Alembic commands ###



