"""add azurites column to user table

Revision ID: 524bf556bd68
Revises: ba895e40213d
Create Date: 2025-06-10 13:36:58.148330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '524bf556bd68'
down_revision: Union[str, None] = 'ba895e40213d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('azurites', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'azurites')
    # ### end Alembic commands ###
