"""Complete schema with limit breaks

Revision ID: 9f3194b9c0d2
Revises: 
Create Date: 2025-06-13 10:09:12.897520

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f3194b9c0d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('esprit_data',
    sa.Column('esprit_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rarity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('class_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('visual_asset_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_hp', sa.Integer(), nullable=False),
    sa.Column('base_attack', sa.Integer(), nullable=False),
    sa.Column('base_defense', sa.Integer(), nullable=False),
    sa.Column('base_speed', sa.Float(), nullable=False),
    sa.Column('base_magic_resist', sa.Integer(), nullable=False),
    sa.Column('base_crit_rate', sa.Float(), nullable=False),
    sa.Column('base_block_rate', sa.Float(), nullable=False),
    sa.Column('base_dodge_chance', sa.Float(), nullable=False),
    sa.Column('base_mana_regen', sa.Float(), nullable=False),
    sa.Column('base_mana', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('esprit_id')
    )
    op.create_index(op.f('ix_esprit_data_class_name'), 'esprit_data', ['class_name'], unique=False)
    op.create_index(op.f('ix_esprit_data_esprit_id'), 'esprit_data', ['esprit_id'], unique=False)
    op.create_index(op.f('ix_esprit_data_name'), 'esprit_data', ['name'], unique=False)
    op.create_index(op.f('ix_esprit_data_rarity'), 'esprit_data', ['rarity'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('faylen', sa.Integer(), nullable=False),
    sa.Column('virelite', sa.Integer(), nullable=False),
    sa.Column('fayrites', sa.Integer(), nullable=False),
    sa.Column('fayrite_shards', sa.Integer(), nullable=False),
    sa.Column('remna', sa.Integer(), nullable=False),
    sa.Column('ethryl', sa.Integer(), nullable=False),
    sa.Column('loot_chests', sa.Integer(), nullable=False),
    sa.Column('last_daily_claim', sa.DateTime(), nullable=True),
    sa.Column('last_daily_summon', sa.DateTime(), nullable=True),
    sa.Column('pity_count_standard', sa.Integer(), nullable=False),
    sa.Column('pity_count_premium', sa.Integer(), nullable=False),
    sa.Column('active_esprit_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('support1_esprit_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('support2_esprit_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_level'), 'users', ['level'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('user_esprits',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('esprit_data_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_hp', sa.Integer(), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.Column('current_xp', sa.Integer(), nullable=False),
    sa.Column('limit_breaks_performed', sa.Integer(), nullable=False),
    sa.Column('stat_boost_multiplier', sa.Float(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['esprit_data_id'], ['esprit_data.esprit_id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_esprits_current_level'), 'user_esprits', ['current_level'], unique=False)
    op.create_index(op.f('ix_user_esprits_esprit_data_id'), 'user_esprits', ['esprit_data_id'], unique=False)
    op.create_index(op.f('ix_user_esprits_owner_id'), 'user_esprits', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_esprits_owner_id'), table_name='user_esprits')
    op.drop_index(op.f('ix_user_esprits_esprit_data_id'), table_name='user_esprits')
    op.drop_index(op.f('ix_user_esprits_current_level'), table_name='user_esprits')
    op.drop_table('user_esprits')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_level'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_esprit_data_rarity'), table_name='esprit_data')
    op.drop_index(op.f('ix_esprit_data_name'), table_name='esprit_data')
    op.drop_index(op.f('ix_esprit_data_esprit_id'), table_name='esprit_data')
    op.drop_index(op.f('ix_esprit_data_class_name'), table_name='esprit_data')
    op.drop_table('esprit_data')
    # ### end Alembic commands ###
