"""Add level_cap to User table

Revision ID: d20101d10889
Revises: 876c0f07b1b6
Create Date: 2025-06-15 06:06:03.167162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd20101d10889'
down_revision: Union[str, None] = '876c0f07b1b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('level_cap', sa.Integer(), nullable=False, server_default='10'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'level_cap')
    # ### end Alembic commands ###
