"""Remove current_xp from UserEsprit

Revision ID: fea3f4f37bd4
Revises: 9f3194b9c0d2
Create Date: 2025-06-13 21:44:09.650773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fea3f4f37bd4'
down_revision: Union[str, None] = '9f3194b9c0d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_esprits', 'current_xp')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_esprits', sa.Column('current_xp', sa.INTEGER(), autoincrement=False, nullable=True, server_default=sa.text('0')))
    # ### end Alembic commands ###
